#!/bin/bash
# This will compile all the necessary utilities to run WRF-Chem and
# prepare its input.

mydir=`dirname $0`
cd $mydir
mydir=`pwd -P`

# Make sure the folder for the compilation logs exists
if [ ! -d "$mydir/COMPLOGS" ]; then
    mkdir "$mydir/COMPLOGS"
fi

# Also make sure to source the environmental variables
. "$mydir/envvar_wrfchem.cfg"

# The exit status needs to reflect which compilations succeeded
# start as 11111 (= 31) and remove the corresponding bit as each
# one succeeds
exitstat=31

# First WRF-Chem
cd ../WRFV3
wrfcomp=false
echo ""
echo "Compiling WRF-Chem..."
if [ ! -f configure.wrf ]; then
    echo "  ERROR: configure.wrf is not present; cannot compile WRF."
    echo "  Run 'autowrfchem config' to produce the necessary file."
    echo "  Remember, the clean command removes the configure.wrf file."
else
    ./compile em_real >& "$mydir/COMPLOGS/compile_wrf.log"
    wrfexit=$?
    if [ $wrfexit -eq 0 ]; then
        wrfcomp=true
        exitstat=$((exitstat - 1))
    fi
fi

# Next WPS. Only compile if WRF successfully did.
cd ../WPS
echo ""
echo "Compiling WPS..."
if $wrfcomp; then
    if [ ! -f configure.wps ]; then
        echo "ERROR: configure.wps is not present; cannot compile WPS."
        echo "Run 'autowrfchem config' to produce the necessary file."
        echo "Remember, the clean command removes the configure.wps file."
    else
        ./compile >& "$mydir/COMPLOGS/compile_wps.log" 
        wpsexit=$?
        if [ $wpsexit -eq 0 ]; then
            # WPS has 3 pieces so double check that all of them were created
            wpssecc=true
            if [ ! -f geogrid.exe ]; then
                echo "geogrid did not compile"
                wpssecc=false
            fi
            if [ ! -f ungrib.exe ]; then
                echo "ungrib did not compile"
                wpssecc=false
            fi
            if [ ! -f metgrid.exe ]; then
                echo "metgrid did not compile"
                wpssecc=false
            fi

            if $wpssucc; then
                exitstat=$((exitstat - 2))
            fi
        fi
    fi
else
    echo "  Cannot compile WPS if WRF did not compile. Skipping for"
    echo "  now. Check the compile logs in"
    echo "  $mydir/COMPLOGS"
    echo "  to see why WRF failed to build and correct that issue before"
    echo "  rerunning 'autowrfchem compile'"
fi

# Now FINN
cd ../FINN/src
echo ""
echo "Compiling mfire_emis..."
./make_fire_emis >& "$mydir/COMPLOGS/compile_finn.log"
finnexit=$?
if [ $finnexit -eq 0 ]; then
    exitstat=$((exitstat - 4))
fi

# Now MEGAN
cd ../../MEGAN/src
echo ""
echo "Compiling megan_bio_emiss..."
./make_util megan_bio_emiss >& "$mydir/COMPLOGS/compile_megan.log"
meganexit=$?
if [ $meganexit -eq 0 ]; then
    exitstat=$((exitstat - 8))
fi

# And MOZBC
cd ../../MOZBC/src
echo ""
echo "Compiling MOZBC..."
./make_mozbc >& "$mydir/COMPLOGS/compile_mozbc.log"
mozbcexit=$?
if [ $mozbcexit -eq 0 ]; then
    exitstat=$((exitstat - 16))
fi

exit $exitstat
