#!/bin/bash
# Okay, this one will not be too bad. All it needs to do is
# go into the MEIC directory and run it.
# This will however handle the copying and linking of the wrfem
# files in the run directory
cd `dirname $0`
mydir=`pwd -P`

cd "$mydir/../../MEIC/src"
python ./mozart.py
emissexit=$?

# Ensure that the WPS namelist is linked to the one in the CONFIG folder
if [ -e namelist.wps ]; then
    # Back up only if not a link already
    lnk=`readlink namelist.wps`
    if [ ! -z $lnk ]; then
        mv namelist.wps namelist.wps.autowrf-backup
    fi
fi

ln -s "$mydir/../CONFIG/namelist.wps"

if [ $emissexit -ne 0 ]; then
    echo "mozart.py failed with exit code $emissexit"
    exit 1
fi

for f in wrfchemi*; do
    if [ -f "../../../WRFV3/run/$f" ]; then
        mv "../../../WRFV3/run/${f}" "../../../WRFV3/run/${f}.autowrf-backup"
    fi
done

cp wrfchemi* ../../../WRFV3/run

# Link the output to make it easier to find
#cd "$mydir/../PREPLOGS"
#ln -sf ../../NEI/src/v04/al2radm2.outp emiss.log

exit 0
